@startuml
package data{


    class Manager{
    The manager seperates the storage of data from the rest of the program.
    Also does calculation like, spend this month, to be budgeted, etc
    storage outsourced to submanagers.
    ----

    ----
    }

    class Record{
      int id
      date date
      int amount
      account account
      envelope category
      String description
      String benefit

      --
      Describes a single transaction
    }



    class Account {
      int id
      string name
      string description
      --
      stores account information
    }


    class Envelope{
      --
      stores how much is budgeted
      for a specific category in a certain month.
    }
    class SAVE{

    --
    read and write's data to disk
    }
    class EnvelopeMonth{
        Identifier for month and year
    }

    class BudgetGoal{
        Stores budgetGoal
    }
}


class GUI{

    --
    presents data to user
    implementation and design pending.
    }



GUI -- Manager
SAVE - Manager
Manager -- Account
Manager -- Envelope
Account -- Record
Envelope -- BudgetGoal
Envelope -- EnvelopeMonth
@enduml

